import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import { type ContainerBuilder, MessageFlags } from "discord.js";
import {
  buildReleaseNotePages,
  compareVersions,
  EMPTY_SECTION_TEXT,
  formatVersion,
  loadReleaseNotes,
  parseChangelog,
  parseVersion,
  type ReleaseSection,
  type Version,
} from "../../../src/services/releaseNotes";
import {
  MAX_TOTAL_BYTES_PER_MESSAGE,
  MAX_TOTAL_CHARS_PER_MESSAGE,
} from "../../../src/utils/chatContainerBuilder";

const REPO_CHANGELOG = join(import.meta.dir, "..", "..", "..", "CHANGELOG.md");

function v(text: string): Version {
  const version = parseVersion(text);
  if (!version) throw new Error(`bad version ${text}`);
  return version;
}

function okBody(section: ReleaseSection | undefined): string {
  if (section?.status !== "ok") throw new Error(`expected an ok section, got ${section?.status}`);
  return section.body;
}

function pageText(page: ReturnType<typeof buildReleaseNotePages>[number]): string {
  const container = (page.components as ContainerBuilder[])[0];
  if (!container) throw new Error("no container");
  return container.components
    .map((c) => (c.toJSON() as { content?: string }).content ?? "")
    .join("\n");
}

describe("parseVersion", () => {
  test("accepts x.y.z with or without a leading v", () => {
    expect(parseVersion("1.2.3")).toEqual({ major: 1, minor: 2, patch: 3 });
    expect(parseVersion("v10.0.12")).toEqual({ major: 10, minor: 0, patch: 12 });
  });

  test("rejects prerelease, build, and partial versions", () => {
    for (const input of ["1.2.3-rc.1", "1.2.3+build", "1.2", "latest", ""]) {
      expect(parseVersion(input)).toBeUndefined();
    }
  });

  test("compares numerically", () => {
    expect(compareVersions(v("1.10.0"), v("1.9.9"))).toBeGreaterThan(0);
    expect(compareVersions(v("1.3.4"), v("1.4.0"))).toBeLessThan(0);
    expect(compareVersions(v("2.0.0"), v("2.0.0"))).toBe(0);
  });
});

describe("parseChangelog", () => {
  const sample = [
    "# Changelog",
    "",
    "## [Unreleased]",
    "",
    "- not released",
    "",
    "## [1.2.0] - 2026-01-02",
    "",
    "### Added",
    "",
    "- new thing (#3)",
    "",
    "```md",
    "## [9.9.9] - 2026-01-01",
    "```",
    "",
    "## [1.1.0] - 2026-01-01",
    "",
    "## [1.0.0] - 2025-12-31",
    "",
    "- first",
    "",
    "<!-- ends the last list, so the link definitions below are not read as part of its final item -->",
    "",
    "[1.2.0]: https://github.com/example/compare/v1.1.0...v1.2.0",
    "",
    "<!-- generated by git-cliff -->",
  ].join("\n");

  test("lists released versions newest first and skips Unreleased", () => {
    expect(parseChangelog(sample).versions().map(formatVersion)).toEqual([
      "1.2.0",
      "1.1.0",
      "1.0.0",
    ]);
  });

  test("keeps a heading inside a code fence as body text", () => {
    const notes = parseChangelog(sample);
    expect(notes.section(v("9.9.9"))).toBeUndefined();
    expect(okBody(notes.section(v("1.2.0")))).toContain("## [9.9.9] - 2026-01-01");
  });

  test("stops the last section before the git-cliff footer and link definitions", () => {
    expect(okBody(parseChangelog(sample).section(v("1.0.0")))).toBe("- first");
  });

  test("an empty section is ok with an empty body", () => {
    const section = parseChangelog(sample).section(v("1.1.0"));
    expect(section).toEqual({ version: v("1.1.0"), date: "2026-01-01", body: "", status: "ok" });
  });

  test("reads CRLF the same as LF", () => {
    const crlf = parseChangelog(sample.replaceAll("\n", "\r\n"));
    expect(okBody(crlf.section(v("1.0.0")))).toBe("- first");
    expect(crlf.versions()).toHaveLength(3);
  });

  test("a repeated version heading marks that version as duplicate", () => {
    const notes = parseChangelog(`${sample}\n## [1.2.0] - 2026-02-02\n\n- again\n`);
    expect(notes.section(v("1.2.0"))).toEqual({ version: v("1.2.0"), status: "duplicate" });
    expect(notes.versions().map(formatVersion)).toEqual(["1.2.0", "1.1.0", "1.0.0"]);
  });

  test("an unclosed fence does not throw and keeps later lines in the section", () => {
    const notes = parseChangelog("## [1.0.0] - 2025-01-01\n\n```\n## [0.9.0] - 2024-01-01\n");
    expect(notes.versions().map(formatVersion)).toEqual(["1.0.0"]);
    expect(okBody(notes.section(v("1.0.0")))).toContain("## [0.9.0]");
  });

  test("parses the repository CHANGELOG", async () => {
    const notes = await loadReleaseNotes(REPO_CHANGELOG);
    if (!notes) throw new Error("CHANGELOG.md could not be read");
    const versions = notes.versions();
    expect(versions.length).toBeGreaterThanOrEqual(15);
    expect(formatVersion(versions.at(-1) ?? v("0.0.0"))).toBe("1.0.0");
    for (const version of versions) {
      const body = okBody(notes.section(version));
      expect(body).not.toContain("<!--");
      expect(body).not.toMatch(/^\[\d+\.\d+\.\d+\]: /m);
    }
  });
});

describe("loadReleaseNotes", () => {
  test("returns undefined for a missing file", async () => {
    expect(await loadReleaseNotes(join(import.meta.dir, "no-such-CHANGELOG.md"))).toBeUndefined();
  });
});

describe("buildReleaseNotePages", () => {
  test("puts the title on the first page only and keeps every page within the limits", () => {
    const body = Array.from(
      { length: 120 },
      (_, i) => `- 会話履歴を Discord から読む変更の ${i + 1} 番目の項目 (#${i})`,
    ).join("\n");
    const pages = buildReleaseNotePages(v("1.5.0"), body);
    expect(pages.length).toBeGreaterThan(1);
    pages.forEach((page, index) => {
      const text = pageText(page);
      expect(text.length).toBeLessThanOrEqual(MAX_TOTAL_CHARS_PER_MESSAGE);
      expect(Buffer.byteLength(text)).toBeLessThanOrEqual(MAX_TOTAL_BYTES_PER_MESSAGE);
      expect(text.startsWith("## DisQord v1.5.0 の変更点")).toBe(index === 0);
    });
  });

  test("every page is Components V2 and mentions nobody", () => {
    const pages = buildReleaseNotePages(v("1.5.0"), "- @everyone を含む PR タイトル (#1)");
    for (const page of pages) {
      expect(page.allowedMentions).toEqual({ parse: [] });
      expect(Number(page.flags) & MessageFlags.IsComponentsV2).toBe(MessageFlags.IsComponentsV2);
      expect(Number(page.flags) & MessageFlags.Ephemeral).toBe(0);
    }
  });

  test("an empty section says so", () => {
    const [page] = buildReleaseNotePages(v("1.1.0"), "");
    if (!page) throw new Error("no page");
    expect(pageText(page)).toContain(EMPTY_SECTION_TEXT);
  });
});
